prestiges:
  1:
    cost: 5000000
    grantperms:
      - essentials.warp.prestige1
votelinks:
  - 'https://example.com/vote'
  - 'https://example.com/vote2'
settings:
  lastRankGroupName: test
  backpackBarFormat: "&bYour backpack: &6%amount%&b/&6%max% &bBlocks"
