name: PrisonCore
version: '${project.version}'
main: com.github.carthax08.servercore.Main
authors: [ CarThax08 ]
api-version: 1.18
depend: [Vault, LuckPerms]
softdepend: [PlaceholderAPI]
commands:
  novacoins:
    description: See how many NovaCoins you have
    usage: /tokens
    aliases: [coins, nc, c, ncoins]
  prestige:
    description: Prestige to restart with a money boost!
    usage: /prestige
  autosmelt:
    description: Toggle AutoSmelt
  autosell:
    description: Toggle AutoSell
    usage: /autosell
  coinshop:
    description: Buy items with tokens!
    usage: /coinshop
    aliases: [cs, cshop]
  sellall:
    description: Sell all your items!
    usage: /sellall
  vote:
    description: Get the links to vote for our server!
    usage: /vote
  rankup:
    description: Go up through the ranks!
    usage: /rankup
  backpacksize:
    description: Change a player's backpack size
    usage: /backpacksize [player] [add, set, remove] [amount]
    aliases: [bps, bpsize]
  prisoncorereload:
    description: Reloads the config files for PrisonCore
    usage: /prisoncorereload
    aliases: [pcr, pcreload]