name: PrisonCore
version: '${project.version}'
main: com.github.carthax08.servercore.Main
authors: [ CarThax08 ]
api-version: 1.18
depend: [Vault, LuckPerms]
softdepend: [PlaceholderAPI]
commands:
  tokens:
    description: Token command
    usage: /tokens [add, set, remove, clear] [player] [amount]
  prestige:
    description: Prestige to restart with a money boost!
    usage: /prestige
  autosmelt:
    description: Toggle Autosmelt
  enchants:
    description: Enchants command
  crates:
    description: Buy crate keys with tokens!
    usage: /crates
  sellall:
    description: Sell all your items!
    usage: /sellall
  vote:
    description: Get the links to vote for our server!
    usage: /vote
  rankup:
    description: Go up through the ranks!
    usage: /rankup